name: check.yml

on: [push, pull_request]

env:
  PYTHON: 3.11

jobs:

  check-pylint:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ env.PYTHON }}

    - name: Install
      run: |
        pip install pylint
        pip install .

    - name: Check
      run: |
        pylint src

  check-pyright:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ env.PYTHON }}

    - name: Install
      run: |
        pip install pyright
        pip install .

    - name: Check
      run: |
        pyright src

  check-flake8:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ env.PYTHON }}

    - name: Install
      run: |
        pip install flake8
        pip install .

    - name: Check
      run: |
        flake8 src
