name: publish.yml

on: [push]

env:
  PYTHON: 3.11

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ env.PYTHON }}

    - name: Install
      run: |
        pip install build

    - name: Build
      run: |
        python -m build

    - name: Publish
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
