name: publish.yml

on: [push]

env:
  PYTHON: 3.11

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ env.PYTHON }}

    - name: Install
      run: |
        pip install build

    - name: Build
      run: |
        python -m build

    - name: Publish (pypi.org)
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Publish (test.pypi.org)
      if: ${{ false }}
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy
