name: test.yml

on: [push, pull_request]

env:
  PYTHON: 3.11

jobs:

  test-pypi:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ env.PYTHON }}

    - name: Install
      run: |
        sudo apt update
        sudo apt install --yes libsndfile1
        pip install pytest
        pip install demucs
        pip install .

    - name: Test
      run: |
        pytest

  test-github:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ env.PYTHON }}

    - name: Install
      run: |
        sudo apt update
        sudo apt install --yes libsndfile1
        pip install pytest
        pip install git+https://github.com/adefossez/demucs#egg=demucs
        pip install .

    - name: Test
      run: |
        pytest
