name: test.yml

on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Setup
      uses: actions/setup-python@master
      with:
        python-version: '3.11'

    - name: Install
      run: |
        sudo apt-get install -qy libsndfile1
        pip install pytest
        pip install demucs
        pip install .

    - name: Test
      run: |
        pytest --capture=tee-sys tests
